In [2]:
import numpy as np

In [3]:
filename = "国际数据主要国家(地区)年度数据.csv"

In [4]:
arr = np.genfromtxt(filename, delimiter=",", dtype=bytes)
print(arr)

[[b'Column1' b'Column2' b'Column3' b'Column4' b'Column5' b'Column6'
  b'Column7' b'Column8' b'Column9' b'Column10' b'Column11' b'Column12'
  b'Column13' b'Column14' b'Column15' b'Column16' b'Column17' b'Column18'
  b'Column19' b'Column20' b'Column21' b'Column22' b'Column23' b'Column24'
  b'Column25' b'Column26' b'Column27' b'Column28' b'Column29' b'Column30'
  b'Column31' b'Column32' b'Column33' b'Column34' b'Column35' b'Column36'
  b'Column37' b'Column38' b'Column39' b'Column40' b'Column41' b'Column42'
  b'Column43' b'Column44' b'Column45' b'Column46' b'Column47' b'Column48'
  b'Column49' b'Column50']
 [b'???' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'']
 [b'???' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'']
 [b'???' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'']
 [b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???'
  b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???'
  b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???'
  b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???'
  b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???' b'???']
 [b'???' b'32526562' b'1377237' b'160995642' b'774830' b'423188'
  b'53897154' b'15577899' b'1165300' b'25155317' b'7305700' b'1311050527'
  b'257563815' b'79109272' b'36423395' b'8380100' b'126958472' b'7594547'
  b'3892115' b'6802023' b'5850743' b'587606' b'30331007' b'409163'
  b'2959134' b'28513700' b'4490541' b'188924874' b'' b'100699395'
  b'2235355' b'31540372' b'5535002' b'50617045' b'20966000' b'18502413'
  b'67959359' b'78665830' b'9156963' b'26832215' b'91713300' b''
  b'1184765' b'17544126' b'5956900' b'8481855' b'5373502' b'31298900'
  b'87780' b'4422143']
 [b'???' b'31627506' b'1361930' b'159077513' b'765008' b'417394'
  b'53437159' b'15328136' b'1153658' b'25026772' b'7241700' b'1295291543'
  b'254454778' b'78143644' b'35273293' b'8215700' b'127131800' b'7416083'
  b'3753121' b'6689300' b'5612096' b'577914' b'29901997' b'401000'
  b'2909871' b'28174724' b'4236057' b'185044286' b'' b'99138690'
  b'2172065' b'30886545' b'5469724' b'50423955' b'20771000' b'18772481'
  b'67725979' b'77523788' b'9086139' b'26183676' b'90728900' b''
  b'1157360' b'17289224' b'5835500' b'8295840' b'5307188' b'30757700'
  b'87127' b'4294682']
 [b'???' b'30682500' b'1349427' b'157157394' b'754637' b'411499'
  b'52983829' b'15078564' b'1141652' b'24895705' b'7187500' b'1279498874'
  b'251268276' b'77152445' b'34107366' b'8059500' b'127338621' b'7214832'
  b'3593689' b'6579985' b'5286990' b'568056' b'29465372' b'393000'
  b'2859174' b'27834981' b'3906912' b'181192646' b'' b'97571676'
  b'2101288' b'30201051' b'5399162' b'50219669' b'20585000' b'19322593'
  b'67451422' b'76223639' b'9039978' b'25533217' b'89759500' b''
  b'1129315' b'17035275' b'5719600' b'8111894' b'5240088' b'30243200'
  b'86462' b'4169506']
 [b'???' b'29726803' b'1333577' b'155257387' b'743711' b'405512'
  b'52543841' b'14832255' b'1129303' b'24763353' b'7154600' b'1263589639'
  b'248037853' b'76156975' b'32957622' b'7910500' b'127561489' b'6994451'
  b'3419581' b'6473050' b'4924257' b'557763' b'29021940' b'385000'
  b'2808339' b'27500515' b'3545192' b'177392252' b'' b'96017322'
  b'2015624' b'29496047' b'5312437' b'50004441' b'20425000' b'19978756'
  b'67164130' b'74849187' b'8952542' b'24882792' b'88809200' b''
  b'1102076' b'16791425' b'5607200' b'7930929' b'5172941' b'29774500'
  b'85779' b'4046901']
 [b'???' b'28809167' b'1306014' b'153405612' b'732246' b'399443'
  b'52125411' b'14593099' b'1116644' b'24631359' b'7071600' b'1247446011'
  b'244808254' b'75184322' b'31867758' b'7765900' b'127817277' b'6760371'
  b'3239181' b'6366909' b'4591698' b'546682' b'28572970' b'377000'
  b'2759074' b'27179237' b'3210003' b'173669648' b'' b'94501233'
  b'1905437' b'28788438' b'5183688' b'49779000' b'20271000' b'20501167'
  b'66902958' b'73517002' b'8734722' b'24234940' b'87860300' b''
  b'1077602' b'16558676' b'5514600' b'7753925' b'5106672' b'29341200'
  b'85069' b'3927051']
 [b'???' b'27962207' b'1261319' b'151616777' b'720246' b'393302'
  b'51733013' b'14363586' b'1103647' b'24500506' b'7067800' b'1230984504'
  b'241613126' b'74253373' b'30868156' b'7623600' b'128070000' b'6517912'
  b'3059473' b'6260544' b'4337156' b'543656' b'28119500' b'367000'
  b'2712657' b'26875910' b'2943747' b'170043918' b'' b'93038902'
  b'1765513' b'28090647' b'5076732' b'49410000' b'20119000' b'20720602'
  b'66692024' b'72310416' b'8329453' b'23591972' b'86932500' b''
  b'1057122' b'16323287' b'5447900' b'7581696' b'5041995' b'28562400'
  b'84327' b'3811102']
 [b'???' b'27207291' b'1196774' b'149905836' b'707830' b'387080'
  b'51369725' b'14144337' b'1090486' b'24371806' b'7003700' b'1214182182'
  b'238465165' b'73370982' b'29970634' b'7485600' b'128047000' b'6266865'
  b'2881243' b'6153153' b'4181742' b'521405' b'27661017' b'360000'
  b'2669572' b'26592666' b'2762073' b'166520983' b'' b'91641881'
  b'1591151' b'27409491' b'4987573' b'49182000' b'19968000' b'20566871'
  b'66548197' b'71261307' b'7705423' b'22954226' b'86025000' b''
  b'1041827' b'16093481' b'5383300' b'7414960' b'4978960' b'27767400'
  b'83548' b'3702218']
 [b'???' b'26528741' b'1115777' b'148252473' b'694990' b'380786'
  b'51030006' b'13933660' b'1077010' b'24243829' b'6977700' b'1197070109'
  b'235360765' b'72530693' b'29163327' b'7308800' b'128063000' b'6010035'
  b'2705290' b'6045439' b'4109389' b'507274' b'27197419' b'362000'
  b'2629666' b'26325183' b'2652281' b'163096985' b'' b'90297115'
  b'1388962' b'26742842' b'4839396' b'48949000' b'19817000' b'20097057'
  b'66453255' b'70344357' b'6900142' b'22322699' b'85118700' b''
  b'1030915' b'15673999' b'5318700' b'7254072' b'4917541' b'27302700'
  b'82737' b'3596688']
 [b'???' b'25877544' b'1026568' b'146592687' b'681471' b'374459'
  b'50698814' b'13728700' b'1063040' b'24111945' b'6925900' b'1179685631'
  b'232296830' b'71720859' b'28423538' b'7180100' b'128001000' b'5759424'
  b'2538591' b'5939634' b'4085426' b'493022' b'26730607' b'349000'
  b'2592776' b'26063619' b'2593750' b'159767672' b'' b'88965508'
  b'1178955' b'26083522' b'4588599' b'48598000' b'19668000' b'19425597'
  b'66353572' b'69515492' b'6010100' b'21701105' b'84218500' b''
  b'1021235' b'15484192' b'5268400' b'7099021' b'4858235' b'26868000'
  b'81914' b'3494496']
 [b'???' b'25183615' b'940808' b'144839238' b'666920' b'368150'
  b'50355559' b'13525360' b'1048293' b'23969897' b'6857100' b'1162088305'
  b'229263980' b'70923164' b'27716983' b'7053700' b'127854000' b'5530218'
  b'2389498' b'5838837' b'4057041' b'479728' b'26263048' b'333000'
  b'2558484' b'25794344' b'2553376' b'156524189' b'' b'87592899'
  b'988448' b'25419994' b'4401365' b'48372000' b'19520000' b'18728200'
  b'66174486' b'68704721' b'5171255' b'21093973' b'83311200' b''
  b'1008389' b'15308085' b'5218400' b'6949566' b'4801594' b'26488200'
  b'81110' b'3406334']
 [b'???' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'']
 [b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b''
  b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'' b'']]

In [177]:
# 1. 取出所有国家的所有年份的人口数据
people_arr = arr[5:-2, 1:]
# 数据清洗，将空字符串替换为 b"0"，再修改数据类型为int
people_arr = np.where(people_arr == b"", b"0", people_arr).astype(np.uint32)
print(people_arr)

[[  32526562    1377237  160995642     774830     423188   53897154
    15577899    1165300   25155317    7305700 1311050527  257563815
    79109272   36423395    8380100  126958472    7594547    3892115
     6802023    5850743     587606   30331007     409163    2959134
    28513700    4490541  188924874          0  100699395    2235355
    31540372    5535002   50617045   20966000   18502413   67959359
    78665830    9156963   26832215   91713300          0    1184765
    17544126    5956900    8481855    5373502   31298900      87780
     4422143]
 [  31627506    1361930  159077513     765008     417394   53437159
    15328136    1153658   25026772    7241700 1295291543  254454778
    78143644   35273293    8215700  127131800    7416083    3753121
     6689300    5612096     577914   29901997     401000    2909871
    28174724    4236057  185044286          0   99138690    2172065
    30886545    5469724   50423955   20771000   18772481   67725979
    77523788    9086139   26183676   90728900          0    1157360
    17289224    5835500    8295840    5307188   30757700      87127
     4294682]
 [  30682500    1349427  157157394     754637     411499   52983829
    15078564    1141652   24895705    7187500 1279498874  251268276
    77152445   34107366    8059500  127338621    7214832    3593689
     6579985    5286990     568056   29465372     393000    2859174
    27834981    3906912  181192646          0   97571676    2101288
    30201051    5399162   50219669   20585000   19322593   67451422
    76223639    9039978   25533217   89759500          0    1129315
    17035275    5719600    8111894    5240088   30243200      86462
     4169506]
 [  29726803    1333577  155257387     743711     405512   52543841
    14832255    1129303   24763353    7154600 1263589639  248037853
    76156975   32957622    7910500  127561489    6994451    3419581
     6473050    4924257     557763   29021940     385000    2808339
    27500515    3545192  177392252          0   96017322    2015624
    29496047    5312437   50004441   20425000   19978756   67164130
    74849187    8952542   24882792   88809200          0    1102076
    16791425    5607200    7930929    5172941   29774500      85779
     4046901]
 [  28809167    1306014  153405612     732246     399443   52125411
    14593099    1116644   24631359    7071600 1247446011  244808254
    75184322   31867758    7765900  127817277    6760371    3239181
     6366909    4591698     546682   28572970     377000    2759074
    27179237    3210003  173669648          0   94501233    1905437
    28788438    5183688   49779000   20271000   20501167   66902958
    73517002    8734722   24234940   87860300          0    1077602
    16558676    5514600    7753925    5106672   29341200      85069
     3927051]
 [  27962207    1261319  151616777     720246     393302   51733013
    14363586    1103647   24500506    7067800 1230984504  241613126
    74253373   30868156    7623600  128070000    6517912    3059473
     6260544    4337156     543656   28119500     367000    2712657
    26875910    2943747  170043918          0   93038902    1765513
    28090647    5076732   49410000   20119000   20720602   66692024
    72310416    8329453   23591972   86932500          0    1057122
    16323287    5447900    7581696    5041995   28562400      84327
     3811102]
 [  27207291    1196774  149905836     707830     387080   51369725
    14144337    1090486   24371806    7003700 1214182182  238465165
    73370982   29970634    7485600  128047000    6266865    2881243
     6153153    4181742     521405   27661017     360000    2669572
    26592666    2762073  166520983          0   91641881    1591151
    27409491    4987573   49182000   19968000   20566871   66548197
    71261307    7705423   22954226   86025000          0    1041827
    16093481    5383300    7414960    4978960   27767400      83548
     3702218]
 [  26528741    1115777  148252473     694990     380786   51030006
    13933660    1077010   24243829    6977700 1197070109  235360765
    72530693   29163327    7308800  128063000    6010035    2705290
     6045439    4109389     507274   27197419     362000    2629666
    26325183    2652281  163096985          0   90297115    1388962
    26742842    4839396   48949000   19817000   20097057   66453255
    70344357    6900142   22322699   85118700          0    1030915
    15673999    5318700    7254072    4917541   27302700      82737
     3596688]
 [  25877544    1026568  146592687     681471     374459   50698814
    13728700    1063040   24111945    6925900 1179685631  232296830
    71720859   28423538    7180100  128001000    5759424    2538591
     5939634    4085426     493022   26730607     349000    2592776
    26063619    2593750  159767672          0   88965508    1178955
    26083522    4588599   48598000   19668000   19425597   66353572
    69515492    6010100   21701105   84218500          0    1021235
    15484192    5268400    7099021    4858235   26868000      81914
     3494496]
 [  25183615     940808  144839238     666920     368150   50355559
    13525360    1048293   23969897    6857100 1162088305  229263980
    70923164   27716983    7053700  127854000    5530218    2389498
     5838837    4057041     479728   26263048     333000    2558484
    25794344    2553376  156524189          0   87592899     988448
    25419994    4401365   48372000   19520000   18728200   66174486
    68704721    5171255   21093973   83311200          0    1008389
    15308085    5218400    6949566    4801594   26488200      81110
     3406334]]

In [178]:
# 2. 获取所有国家的名称
country_list = [country.decode("utf-8") for country in arr[4, 1:]]
#print(country_list)
country_arr = np.array(country_list)
print(country_arr)

['阿富汗' '巴林' '孟加拉国' '不丹' '文莱' '缅甸' '柬埔寨' '塞浦路斯' '朝鲜' '中国香港' '印度' '印度尼西亚'
 '伊朗' '伊拉克' '以色列' '日本' '约旦' '科威特' '老挝' '黎巴嫩' '中国澳门' '马来西亚' '马尔代夫' '蒙古'
 '尼泊尔' '阿曼' '巴基斯坦' '巴勒斯坦' '菲律宾' '卡塔尔' '沙特阿拉伯' '新加坡' '韩国' '斯里兰卡' '叙利亚' '泰国'
 '土耳其' '阿联酋' '也门' '越南' '中国台湾' '东帝汶' '哈萨克斯坦' '吉尔吉斯斯坦' '塔吉克斯坦' '土库曼斯坦'
 '乌兹别克斯坦' '马恩岛' '约旦河西岸和加沙']

In [179]:
# 3. 获取年份的名称
year_list = [year.decode("utf-8") for year in arr[5:-2, 0]]
year_arr = np.array(year_list)
print(year_arr)

['2015年' '2014年' '2013年' '2012年' '2011年' '2010年' '2009年' '2008年' '2007年'
 '2006年']

## 1. 统计2015年各个国家人口数据

In [171]:
year = "2015年"
#print(year_list.index(year))
# 查找数组中指定元素的下标，返回一个二维数组，通过[0, 0]
# 表示people_arr的行
year_index = np.argwhere(year_arr == year)[0, 0]

for country, people in zip(country_arr, people_arr[year_index]):
    print("{} : {}".format(country, people))

阿富汗 : 32526562
巴林 : 1377237
孟加拉国 : 160995642
不丹 : 774830
文莱 : 423188
缅甸 : 53897154
柬埔寨 : 15577899
塞浦路斯 : 1165300
朝鲜 : 25155317
中国香港 : 7305700
印度 : 1311050527
印度尼西亚 : 257563815
伊朗 : 79109272
伊拉克 : 36423395
以色列 : 8380100
日本 : 126958472
约旦 : 7594547
科威特 : 3892115
老挝 : 6802023
黎巴嫩 : 5850743
中国澳门 : 587606
马来西亚 : 30331007
马尔代夫 : 409163
蒙古 : 2959134
尼泊尔 : 28513700
阿曼 : 4490541
巴基斯坦 : 188924874
巴勒斯坦 : 0
菲律宾 : 100699395
卡塔尔 : 2235355
沙特阿拉伯 : 31540372
新加坡 : 5535002
韩国 : 50617045
斯里兰卡 : 20966000
叙利亚 : 18502413
泰国 : 67959359
土耳其 : 78665830
阿联酋 : 9156963
也门 : 26832215
越南 : 91713300
中国台湾 : 0
东帝汶 : 1184765
哈萨克斯坦 : 17544126
吉尔吉斯斯坦 : 5956900
塔吉克斯坦 : 8481855
土库曼斯坦 : 5373502
乌兹别克斯坦 : 31298900
马恩岛 : 87780
约旦河西岸和加沙 : 4422143

## 2. 统计朝鲜历史各个时期人口数据

In [101]:
country = "朝鲜"
country_index = np.argwhere(country_arr == country)[0, 0]
print(country_index)

8

In [102]:
# print(people_arr[:, country_index])

print("{}人口数据".format(country))
for year, people in zip(year_arr, people_arr[:, country_index]):
    print("{} : {}".format(year, people))

朝鲜人口数据
2015年 : 25155317
2014年 : 25026772
2013年 : 24895705
2012年 : 24763353
2011年 : 24631359
2010年 : 24500506
2009年 : 24371806
2008年 : 24243829
2007年 : 24111945
2006年 : 23969897

## 3. 统计缅甸2014年的人口数据

In [103]:
year = "2014年"
country = "缅甸"

year_index = np.argwhere(year_arr == year)[0, 0]
country_index = np.argwhere(country_arr == country)[0, 0]

In [104]:
print("{} 在 {}的人口数据：{}".format(country, year, people_arr[year_index, country_index]))

缅甸 在 2014年的人口数据：53437159

## 4. 统计每一个国家历史平均人口数据

In [105]:
for country, people in zip(country_arr, np.mean(people_arr, axis=0)):
    print("{:10}\t历史平均人口数据：\t {}".format(country, people))

阿富汗       	历史平均人口数据：	 28613193.6
巴林        	历史平均人口数据：	 1226943.1
孟加拉国      	历史平均人口数据：	 152710055.9
不丹        	历史平均人口数据：	 724188.9
文莱        	历史平均人口数据：	 396081.3
缅甸        	历史平均人口数据：	 52017451.1
柬埔寨       	历史平均人口数据：	 14510559.6
塞浦路斯      	历史平均人口数据：	 1108903.3
朝鲜        	历史平均人口数据：	 24567048.9
中国香港      	历史平均人口数据：	 7079330.0
印度        	历史平均人口数据：	 1238088732.5
印度尼西亚     	历史平均人口数据：	 243313284.2
伊朗        	历史平均人口数据：	 74854572.9
伊拉克       	历史平均人口数据：	 31677207.2
以色列       	历史平均人口数据：	 7698350.0
日本        	历史平均人口数据：	 127684265.9
约旦        	历史平均人口数据：	 6606473.8
科威特       	历史平均人口数据：	 3147178.2
老挝        	历史平均人口数据：	 6314887.4
黎巴嫩       	历史平均人口数据：	 4703653.8
中国澳门      	历史平均人口数据：	 538310.6
马来西亚      	历史平均人口数据：	 28326487.7
马尔代夫      	历史平均人口数据：	 373616.3
蒙古        	历史平均人口数据：	 2745874.7
尼泊尔       	历史平均人口数据：	 27085487.9
阿曼        	历史平均人口数据：	 3289393.2
巴基斯坦      	历史平均人口数据：	 172217745.3
巴勒斯坦      	历史平均人口数据：	 0.0
菲律宾       	历史平均人口数据：	 93946462.1
卡塔尔       	历史平均人口数据：	 1734279.8
沙特阿拉伯     	历史平均人口数据：	 28465894.9
新加坡       	历史平均人口数据：	 5079367.8
韩国        	历史平均人口数据：	 49555511.0
斯里兰卡      	历史平均人口数据：	 20211000.0
叙利亚       	历史平均人口数据：	 19661573.7
泰国        	历史平均人口数据：	 66942538.2
土耳其       	历史平均人口数据：	 73291573.9
阿联酋       	历史平均人口数据：	 7908671.7
也门        	历史平均人口数据：	 23933081.5
越南        	历史平均人口数据：	 87447710.0
中国台湾      	历史平均人口数据：	 0.0
东帝汶       	历史平均人口数据：	 1081060.6
哈萨克斯坦     	历史平均人口数据：	 16410177.0
吉尔吉斯斯坦    	历史平均人口数据：	 5527050.0
塔吉克斯坦     	历史平均人口数据：	 7687375.8
土库曼斯坦     	历史平均人口数据：	 5079871.6
乌兹别克斯坦    	历史平均人口数据：	 28840420.0
马恩岛       	历史平均人口数据：	 84585.3
约旦河西岸和加沙  	历史平均人口数据：	 3887112.1

## 5. 统计亚洲2015年总人口，及平均人口

In [115]:
year = "2015年"
year_index = np.argwhere(year_arr == year)[0, 0]

print("亚洲在 {} 的总人口: {:.2f}亿 和 平均人口 :{:.2f} ".format(year, np.sum(people_arr[year_index]) / 10 ** 8, np.mean(people_arr[year_index])))

亚洲在 2015年 的总人口: 29.78亿 和 平均人口 :60771695.57

## 6. 统计印度、柬埔寨、阿富汗在2011、2012、2013年总人口及平均人口

In [117]:
country_list = ["印度", "柬埔寨", "阿富汗"]
year_list = ["2011年", "2012年", "2013年"]

In [135]:
country_index_list = [np.argwhere(country_arr == country)[0, 0] for country in country_list]
year_index_list = [np.argwhere(year_arr == year)[0, 0] for year in year_list]
print(country_index_list)
print(year_index_list)

[10, 6, 0]
[4, 3, 2]

In [136]:
# 取不同国家在三年的数据
## 先获取所有国家的 year_list 每一年数据 arr[[0, 2, 4]]
year_list_people_arr = people_arr[year_index_list]
#print(year_list_people_arr)

for country, country_index in zip(country_list, country_index_list):
    print("{} 在 {}".format(country, ",".join(year_list)), end=' ')
    print("总人口 : {}".format(np.sum(year_list_people_arr[:, country_index])), end=' ')
    print("平均人口: {:.2f}".format(np.mean(year_list_people_arr[:, country_index])))

印度 在 2011年,2012年,2013年 总人口 : 3790534524 平均人口: 1263511508.00
柬埔寨 在 2011年,2012年,2013年 总人口 : 44503918 平均人口: 14834639.33
阿富汗 在 2011年,2012年,2013年 总人口 : 89218470 平均人口: 29739490.00

In [137]:
# 取不同年份在三个国家的数据

## 先获取所有国家的 year_list 每一年数据 arr[[0, 2, 4]]
country_list_people_arr = people_arr[:, country_index_list]
#print(country_list_people_arr)

for year, year_index in zip(year_list, year_index_list):
    print("{} 在 {}".format(year, ",".join(country_list)), end=' ')
    print("总人口 : {}".format(np.sum(country_list_people_arr[year_index])), end=' ')
    print("平均人口: {:.2f}".format(np.mean(country_list_people_arr[year_index])))

2011年 在 印度,柬埔寨,阿富汗 总人口 : 1290848277 平均人口: 430282759.00
2012年 在 印度,柬埔寨,阿富汗 总人口 : 1308148697 平均人口: 436049565.67
2013年 在 印度,柬埔寨,阿富汗 总人口 : 1325259938 平均人口: 441753312.67

## 7. 统计任意两个国家之间的人口差数据

In [141]:
country1 = "阿富汗"
country2 = "以色列"
year = "2008年"

country1_index = np.argwhere(country_arr == country1)[0, 0]
country2_index = np.argwhere(country_arr == country2)[0, 0]

people_2008_arr = people_arr[np.argwhere(year_arr == year)[0, 0]]
print(people_2008_arr)

[  26528741    1115777  148252473     694990     380786   51030006
   13933660    1077010   24243829    6977700 1197070109  235360765
   72530693   29163327    7308800  128063000    6010035    2705290
    6045439    4109389     507274   27197419     362000    2629666
   26325183    2652281  163096985          0   90297115    1388962
   26742842    4839396   48949000   19817000   20097057   66453255
   70344357    6900142   22322699   85118700          0    1030915
   15673999    5318700    7254072    4917541   27302700      82737
    3596688]

In [146]:
print("{} 的 {} 的人口数据: {} ".format(year, country1, people_2008_arr[country1_index]))
print("{} 的 {} 的人口数据: {} ".format(year, country2, people_2008_arr[country2_index]))
print("两个国家的差值为: {}".format(people_2008_arr[country1_index] - people_2008_arr[country2_index]))

2008年 的 阿富汗 的人口数据: 26528741
2008年 的 以色列 的人口数据: 7308800
两个国家的差值为: 19219941

## 8 .统计2012年亚洲人口数量排名前10的国家

In [183]:
year = "2012年"
people_2012_arr = people_arr[np.argwhere(year_arr == year)[0, 0]]
print(people_2012_arr)

[  29726803    1333577  155257387     743711     405512   52543841
   14832255    1129303   24763353    7154600 1263589639  248037853
   76156975   32957622    7910500  127561489    6994451    3419581
    6473050    4924257     557763   29021940     385000    2808339
   27500515    3545192  177392252          0   96017322    2015624
   29496047    5312437   50004441   20425000   19978756   67164130
   74849187    8952542   24882792   88809200          0    1102076
   16791425    5607200    7930929    5172941   29774500      85779
    4046901]

In [185]:
# Python的写法

people_dict = dict(enumerate(people_2012_arr))

# sorted() 对字典排序：key表示排序的依据，传入items()每个元素，并按值进行怕需
sorted_data = sorted(people_dict.items(), key = lambda n : n[1])
print(sorted_data)

sorted_index_arr = np.array(sorted_data)[:, 0]
print(sorted_index_arr)

[(27, 0), (40, 0), (47, 85779), (22, 385000), (4, 405512), (20, 557763), (3, 743711), (41, 1102076), (7, 1129303), (1, 1333577), (29, 2015624), (23, 2808339), (17, 3419581), (25, 3545192), (48, 4046901), (19, 4924257), (45, 5172941), (31, 5312437), (43, 5607200), (18, 6473050), (16, 6994451), (9, 7154600), (14, 7910500), (44, 7930929), (37, 8952542), (6, 14832255), (42, 16791425), (34, 19978756), (33, 20425000), (8, 24763353), (38, 24882792), (24, 27500515), (21, 29021940), (30, 29496047), (0, 29726803), (46, 29774500), (13, 32957622), (32, 50004441), (5, 52543841), (35, 67164130), (36, 74849187), (12, 76156975), (39, 88809200), (28, 96017322), (15, 127561489), (2, 155257387), (26, 177392252), (11, 248037853), (10, 1263589639)]

[27 40 47 22  4 20  3 41  7  1 29 23 17 25 48 19 45 31 43 18 16  9 14 44 37
  6 42 34 33  8 38 24 21 30  0 46 13 32  5 35 36 12 39 28 15  2 26 11 10]

In [187]:
# ndarray的写法

# 对数组排序，并返回排序后的索引
sorted_index_arr = people_2012_arr.argsort()
print(sorted_index_arr)

[40 27 47 22  4 20  3 41  7  1 29 23 17 25 48 19 45 31 43 18 16  9 14 44 37
  6 42 34 33  8 38 24 21 30  0 46 13 32  5 35 36 12 39 28 15  2 26 11 10]

In [190]:
# 根据索引取值
sorted_country = country_arr[sorted_index_arr]
sorted_people = people_2012_arr[sorted_index_arr]

In [191]:
data = list(zip(sorted_country, sorted_people))[-10:][::-1]


for country, people in data:
    print(country, people)

印度 1263589639
印度尼西亚 248037853
巴基斯坦 177392252
孟加拉国 155257387
日本 127561489
菲律宾 96017322
越南 88809200
伊朗 76156975
土耳其 74849187
泰国 67164130